<?php echo View::content();
$titulo = "Socios";
$subtitulo = "Actualizar un Socio al BDT"; ?>

<?php echo Html::includeCss(); ?>

<?php echo Form::open(); // por defecto llama a la misma url     ?>

<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Nombre</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <?php echo Form::text('socio.nombre') ?>
    </div>
</div>



<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Sexo</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <?php echo Form::dbSelect('socio.sexo_id'); ?>
    </div>
</div>


<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Tipo Documento</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <?php echo Form::dbSelect('socio.tipodocumento_id'); ?>
    </div>
</div> 

<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Documento</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <?php echo Form::text('socio.nro_doc') ?>
    </div>
</div> 

<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Avatar</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <input type="file">
    </div>
</div> 

<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Fecha de Ingreso</label>
    </div>    
    <div class="col-lg-4 text-center"> 
        <?php echo Form::text('socio.ingreso_at',"readonly"); ?>
    </div>            
</div> 

<div class="row">

    <div class="col-lg-3 text-right"> 
        <label>Saldo</label>
    </div>    
    <div class="col-lg-4 text-center">     
        <?php echo Form::text('socio.saldo',"readonly") ?>
    </div>  
</div> 


<button type="submit" class="btn btn-default">Submit Button</button>
<button type="reset" class="btn btn-default">Reset Button</button>
<?php echo Form::hidden('socio.id') ?>
<?php echo Form::close() ?>