<div class="row">
    <div class="col-lg-12">
        <h1><?php echo $titulo ?></h1>
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-star"></i> <?php echo $subtitulo ?></li>
        </ol>
        <ol class="breadcrumb">
            <li class="active"><a href="/KumbiaPHP/<?php echo $modelo ?>/create"><i class="fa fa-plus-circle"></i> Agregar</a></li>
        </ol>
    </div>
</div><!-- /.row -->

